import { IMAGE_CONST } from '@app/utils/images';

const PROJECTS_LIST = [
  {
    name: 'TEVI APP',
    des: 'One of the most well-designed monetize platform for creators in South East Asia',
    whats: [
      'Art direction',
      'UI/UX design',
      'Icon design',
      'Website development',
      'App Design',
      'System integration',
    ],
    timeline: '2021-2023',
    image: IMAGE_CONST.projects.imageTevi,
    url: 'https://tevi.com/',
  },
  {
    name: 'Marathon Education',
    des: 'An edtech startup based in Vietnam, venture-backed that provide live online tutoring services to K-12 students in Southeast Asia and Vietnam.',
    whats: [
      'Art direction',
      'UI/UX design',
      'Icon design',
      'Website development',
      'App Design',
      'System integration',
    ],
    timeline: '2021-2022',
    image: IMAGE_CONST.projects.imageMarathonEducation,
    url: 'https://marathon.edu.vn/',
  },
  {
    name: 'FPT Play',
    des: 'FPT Play is a versatile streaming platform offering a diverse range of entertainment content, including live TV, movies, and sports, accessible across multiple devices.',
    whats: [
      'Art direction',
      'UI/UX design',
      'Icon design',
      'Website development',
      'App Design',
      'System integration',
    ],
    timeline: '2021-2022',
    image: IMAGE_CONST.projects.imageFptPlay,
    url: 'https://fptplay.vn/',
  },
  {
    name: 'Ngheluon',
    des: 'Ngheluon is an app that provides audiobooks, summaries, and podcasts.',
    whats: [
      'Art direction',
      'UI/UX design',
      'Icon design',
      'Website development',
      'App Design',
      'App Development',
      'System integration',
    ],
    timeline: '2021-2022',
    image: IMAGE_CONST.projects.imageNgheLuon,
    url: '',
  },
  {
    name: 'Tefal',
    des: 'The Tefal homepage serves as the flagship for the brand, providing a range of electronic, refrigeration, and home appliance solutions.',
    whats: [
      'Website development',
      'Campaign marketing',
      'System integration',
    ],
    timeline: '2021-2022',
    image: IMAGE_CONST.projects.imageTefal,
    url: 'https://www.tefal.com.vn/',
  },
  {
    name: 'Asia Vina',
    des: 'Asia Vina is a well-known brand offering a range of household and industrial fan models.',
    whats: [
      'Website development',
      'Campaign marketing',
      'System integration',
    ],
    timeline: '2021-2022',
    image: IMAGE_CONST.projects.imageAsiaVina,
    url: 'https://asiavina.net/',
  },
  {
    name: 'Anlene',
    des: 'Anlene is a well-known milk brand, particularly recognized for its formulations designed for the elderly.',
    whats: [
      'Website development',
      'Campaign marketing',
      'System integration',
    ],
    timeline: '2021-2022',
    image: IMAGE_CONST.projects.imageAnlene,
    url: 'https://www.anlene.com/',
  },
  {
    name: 'THVLi',
    des: 'THVLi is a versatile streaming platform offering a diverse range of entertainment content, including live TV, movies, and sports, accessible across multiple devices.',
    whats: [
      'Art direction',
      'UI/UX design',
      'Icon design',
      'Website development',
      'App Design',
      'System integration',
    ],
    timeline: '2021-2022',
    image: IMAGE_CONST.projects.imageThvl,
    url: 'https://www.thvli.vn/',
  },
];

export { PROJECTS_LIST };
