export const IMAGE_CONST = {
  logo: '/images/common/logo.svg',
  layout: {
    imageFooter: '/images/layout/image-footer.png',
  },
  social: {
    iconFacebook: '/images/social/icon-facebook.svg',
    iconIns: '/images/social/icon-ins.svg',
    iconLinkedin: '/images/social/icon-linkedin.svg',
    iconTevi: '/images/social/icon-tevi.svg',
    iconTiktok: '/images/social/icon-tiktok.svg',
    iconFacebookMb: '/images/social/icon-facebook-mb.svg',
    iconInsMb: '/images/social/icon-ins-mb.svg',
    iconLinkedinMb: '/images/social/icon-linkedin-mb.svg',
    iconTeviMb: '/images/social/icon-tevi-mb.svg',
    iconTiktokMb: '/images/social/icon-tiktok-mb.svg',
  },
  home: {
    backgroundClientSection: '/images/home/background-client-section.png',
    backgroundHeroSection: '/images/home/background-hero-section.png',
    backgroundFeaturesTitle: '/images/home/background-features-title.png',
    bondingTogether: '/images/home/bonding-together.png',
    goWowOrGoHome: '/images/home/go-wow-or-go-home.png',
    purePassion: '/images/home/pure-passion.png',
    resultOriented: '/images/home/result-oriented.png',
    technoMagicians: '/images/home/techno-magicians.png',
    thinkBigMoveForward: '/images/home/think-big-move-forward.png',
    winWinPartnership: '/images/home/win-win-partnership.png',
    logoTevi: '/images/home/logo-tevi.svg',
    logoChamniIsEye: '/images/home/logo-chamni\'s-eye.svg',
    logoNamVietMedia: '/images/home/logo-namviet-media.svg',
    logoUnigon: '/images/home/logo-unigon.svg',
    logoAltamedia: '/images/home/logo-altamedia.svg',
    logoMarathon: '/images/home/logo-marathon.svg',
    logoFptplay: '/images/home/logo-fptplay.svg',
    logoLunarush: '/images/home/logo-lunarush.svg',
    logoUrekaMedia: '/images/home/logo-ureka-media.svg',
    logoNgheLuon: '/images/home/logo-nghe-luon.svg',
    logoTefal: '/images/home/logo-tefal.svg',
    logoAsiaVina: '/images/home/logo-asia-vina.svg',
    logoAnlene: '/images/home/logo-anlene.svg',
    logoThvl: '/images/home/logo-thvl.svg',
  },
  services: {
    backgroundSerHeroSection: '/images/services/background-ser-hero-section.png',
    backgroundSerHow: '/images/services/background-ser-how.png',
    backgroundSerWhy: '/images/services/background-ser-why.png',
    backgroundSerWhyMb: '/images/services/background-ser-why-mb.png',
  },
  projects: {
    imageAnlene: '/images/projects/image-anlene.png',
    imageAsiaVina: '/images/projects/image-asia-vina.png',
    imageFptPlay: '/images/projects/image-fptplay.png',
    imageLunaRush: '/images/projects/image-lunarush.png',
    imageMarathonEducation: '/images/projects/image-marathon-education.png',
    imageNgheLuon: '/images/projects/image-nghe-luon.png',
    imageTefal: '/images/projects/image-tefal.png',
    imageTevi: '/images/projects/image-tevi.png',
    imageThvl: '/images/projects/image-thvl.png',
  },
  contact: {
    backgroundMainContact: '/images/contact/background-main-contact.png',
  },
  privacyPolicy: {
    backgroundHeroPrivacyPolicy: '/images/privacy-policy/background-hero-privacy-policy.png',
  },
};
