export const IMAGE_CONST = {
  logo: '/static/images/common/logo.svg',
  layout: {
    imageFooter: '/static/images/layout/image-footer.png',
  },
  social: {
    iconFacebook: '/static/images/social/icon-facebook.svg',
    iconIns: '/static/images/social/icon-ins.svg',
    iconLinkedin: '/static/images/social/icon-linkedin.svg',
    iconTevi: '/static/images/social/icon-tevi.svg',
    iconTiktok: '/static/images/social/icon-tiktok.svg',
    iconFacebookMb: '/static/images/social/icon-facebook-mb.svg',
    iconInsMb: '/static/images/social/icon-ins-mb.svg',
    iconLinkedinMb: '/static/images/social/icon-linkedin-mb.svg',
    iconTeviMb: '/static/images/social/icon-tevi-mb.svg',
    iconTiktokMb: '/static/images/social/icon-tiktok-mb.svg',
  },
  home: {
    backgroundClientSection: '/static/images/home/background-client-section.png',
    backgroundHeroSection: '/static/images/home/background-hero-section.png',
    backgroundFeaturesTitle: '/static/images/home/background-features-title.png',
    bondingTogether: '/static/images/home/bonding-together.png',
    goWowOrGoHome: '/static/images/home/go-wow-or-go-home.png',
    purePassion: '/static/images/home/pure-passion.png',
    resultOriented: '/static/images/home/result-oriented.png',
    technoMagicians: '/static/images/home/techno-magicians.png',
    thinkBigMoveForward: '/static/images/home/think-big-move-forward.png',
    winWinPartnership: '/static/images/home/win-win-partnership.png',
    logoTevi: '/static/images/home/logo-tevi.svg',
    logoChamniIsEye: '/static/images/home/logo-chamni\'s-eye.svg',
    logoNamVietMedia: '/static/images/home/logo-namviet-media.svg',
    logoUnigon: '/static/images/home/logo-unigon.svg',
    logoAltamedia: '/static/images/home/logo-altamedia.svg',
    logoMarathon: '/static/images/home/logo-marathon.svg',
    logoFptplay: '/static/images/home/logo-fptplay.svg',
    logoLunarush: '/static/images/home/logo-lunarush.svg',
    logoUrekaMedia: '/static/images/home/logo-ureka-media.svg',
    logoNgheLuon: '/static/images/home/logo-nghe-luon.svg',
    logoTefal: '/static/images/home/logo-tefal.svg',
    logoAsiaVina: '/static/images/home/logo-asia-vina.svg',
    logoAnlene: '/static/images/home/logo-anlene.svg',
    logoThvl: '/static/images/home/logo-thvl.svg',
  },
  services: {
    backgroundSerHeroSection: '/static/images/services/background-ser-hero-section.png',
    backgroundSerHow: '/static/images/services/background-ser-how.png',
    backgroundSerWhy: '/static/images/services/background-ser-why.png',
    backgroundSerWhyMb: '/static/images/services/background-ser-why-mb.png',
  },
  projects: {
    imageAnlene: '/static/images/projects/image-anlene.png',
    imageAsiaVina: '/static/images/projects/image-asia-vina.png',
    imageFptPlay: '/static/images/projects/image-fptplay.png',
    imageLunaRush: '/static/images/projects/image-lunarush.png',
    imageMarathonEducation: '/static/images/projects/image-marathon-education.png',
    imageNgheLuon: '/static/images/projects/image-nghe-luon.png',
    imageTefal: '/static/images/projects/image-tefal.png',
    imageTevi: '/static/images/projects/image-tevi.png',
    imageThvl: '/static/images/projects/image-thvl.png',
  },
  contact: {
    backgroundMainContact: '/static/images/contact/background-main-contact.png',
  },
  privacyPolicy: {
    backgroundHeroPrivacyPolicy: '/static/images/privacy-policy/background-hero-privacy-policy.png',
  },
};
